### ISSUE TITLE
Password re-set doesn't work - link is expired immediately

### ISSUE THREAD

**Issue by ajburls** [dwyl/bestevidence#275]
The password re-set function does not work. it immediately says link expired and offers to send a new one which is also expired on immediate use.

![image](https://user-images.githubusercontent.com/30235568/39083086-46aaca3c-4556-11e8-91c1-b7c2c9166b06.png)

**Comment by iteles** [comment]
@ajburls This is ready for you to test!

**Comment by ajburls** [comment]
No, this not working. Immediate use of password re-set returns a link expired notice.

**Comment by iteles** [comment]
@ajburls This is strange! I just tried this in production and it worked for me!
Are you testing this in staging or production Amanda?

**Comment by ajburls** [comment]
@iteles as soon as I saw your message I was convinced I had made a mistake and tested it on the production app. However I have now tested is on the staging version and I get the same problem. However, although I request the link from the staging version it is sending me back to the production version. Have tested three times and each time is the same.

![image](https://user-images.githubusercontent.com/30235568/39241466-e7e13906-487e-11e8-95d2-a3eb07ec5f5e.png)

**Comment by iteles** [comment]
@ajburls That makes sense as we have coded the link to be for production specifically. I'll try to recreate the issue again on my end.

**Comment by ajburls** [comment]
@RobStallion Issue same with completely fresh email address

![image](https://user-images.githubusercontent.com/30235568/39746416-2d4ce45e-52a2-11e8-9d93-75c69f614c4e.png)

**Comment by RobStallion** [comment]
@ajburls Thanks for the update 👍

**Comment by RobStallion** [comment]
Have resolved the issue @ajburls mentioned in [this](https://github.com/dwyl/bestevidence/issues/275#issuecomment-384247036) comment, where the staging site's forgotten password link was redirecting to the live site. It is currently on the password-reset branch but I have deployed that branch to staging and it works as expected. Can be tested. 

However I have been unable to replicate the issue you are having with the password link being expired. The links appear to be working as expected and updating the database as it should, on both staging and live.

@ajburls I am wondering if this could be an issue with the machine that you are currently using. Would you be able to try resetting the password again on a different device this time? Please use the staging site to test it this time if you can as it will now redirect to the correct address.

**Comment by ajburls** [comment]
@RobStallion Just tested using mobile phone and it does go back to staging now but still getting link expired message.

**Comment by ajburls** [comment]
@RobStallion Rob, I just tested this and I get the message with the cut and paste URL so that is working, but a new mini bug has been introduced that wasn't there before - the email address entry box has become case sensitive and gave me the message below when I selected my email address from the dropdown box of email addresses I had used before because it has a capital "A"

![image](https://user-images.githubusercontent.com/30235568/40228835-53701102-5a8a-11e8-8b0e-b68b54724d79.png)

Amanda

**Comment by ajburls** [comment]
@RobStallion I can only log in on the staging app with emails that have the same case each time, so problem is not just when re-setting password. I just checked on the production version and this is not the case so looks like problem has inadvertently been inserted.

**Comment by RobStallion** [comment]
@ajburls Thanks for pointing that out. This fix will be implemented as of the next commit

**Comment by ajburls** [comment]
@RobStallion Couldn't test this on the staging version as I got the error message shown in following screenshot
![image](https://user-images.githubusercontent.com/30235568/40332902-c16121fe-5d4d-11e8-9ac4-3643ce05a6b5.png)

**Comment by ajburls** [comment]
I believe this is now solved and will close. Please re-open if there are outstanding issues
